### ISSUE TITLE
Se debe inicializar la librería antes de cada prueba

### ISSUE THREAD

**Issue by evolentini** [SaEsteva/TP3-Esteva#2]
Cada prueba debe se run ejemplo completo de uso, lo que en este caso implica llamar  a la función `Leds_Create()` antes de cada prueba. La forma mas simple y efectiva es agregar la llamada en la función `setUp()`

https://github.com/SaEsteva/TP3-Esteva/blob/9cea777f7f9bad44f00cdd2efd6b60dae8f4ba3d/test/test_led.c#L8-L10

**Comment by SaEsteva** [comment]
se realizó el cambio sugerido y se comprueba el funcionamiento.
