### ISSUE TITLE
Se puede eliminar esta linea de la prueba

### ISSUE THREAD

**Issue by evolentini** [SaEsteva/TP3-Esteva#3]
Todos los leds arrancan apagados después de la configuración, por lo que esta linea se puede eliminar, después de llamar a la función `Leds_Create()` en la función de `setUp()` 

https://github.com/SaEsteva/TP3-Esteva/blob/9cea777f7f9bad44f00cdd2efd6b60dae8f4ba3d/test/test_led.c#L45

**Comment by SaEsteva** [comment]
Se realiza el cambio y se comprueba funcionamiento.
