### ISSUE TITLE
Solo hace falta una función para consultar el estado del led

### ISSUE THREAD

**Issue by evolentini** [SaEsteva/TP3-Esteva#4]
Solo debe existir una función para consultar el estado, las dos que existen hacen lo mismo, y ademas modifican el estado en lugar de devolver el estado actual del led

**Comment by SaEsteva** [comment]
Se dejó una sola función, la misma toma el puntero (puerto) y realiza un and con la función led_to_bit(LED) y a este resultado lo carga en el puntero que recibe la función. Entiendo que no estaría modificando el estado actual del led, espero no equivocarme en eso.

**Comment by evolentini** [comment]
una observación menor: la función debería declararse como `bool` y no como `_Bool`, para lo cual debes incluir la <stdbool.h> en el archivo de cabeceras `leds.h`. Ademas sería más claro si la función se llamara `Led_IsOn()`
