### ISSUE TITLE
Se puede refactorizar el código

### ISSUE THREAD

**Issue by evolentini** [SaEsteva/TP3-Esteva#5]
Dado que todos los led arrancan apagados sería buena idea reemplazar esta linea

https://github.com/SaEsteva/TP3-Esteva/blob/9cea777f7f9bad44f00cdd2efd6b60dae8f4ba3d/src/leds.c#L16

por una llamada a la función `Led_TurnOffAll()`

**Comment by SaEsteva** [comment]
Se realiza el cambio y se comprueba funcionamiento
